// Code generated by MockGen. DO NOT EDIT.
// Source: ../notary/notary.go

// Package mocks is a generated GoMock package.
package mocks

import (
	notary "github.com/codenotary/ctrlt/pkg/notary"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockNotary is a mock of Notary interface
type MockNotary struct {
	ctrl     *gomock.Controller
	recorder *MockNotaryMockRecorder
}

// MockNotaryMockRecorder is the mock recorder for MockNotary
type MockNotaryMockRecorder struct {
	mock *MockNotary
}

// NewMockNotary creates a new mock instance
func NewMockNotary(ctrl *gomock.Controller) *MockNotary {
	mock := &MockNotary{ctrl: ctrl}
	mock.recorder = &MockNotaryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNotary) EXPECT() *MockNotaryMockRecorder {
	return m.recorder
}

// Start mocks base method
func (m *MockNotary) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start
func (mr *MockNotaryMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockNotary)(nil).Start))
}

// Notarize mocks base method
func (m *MockNotary) Notarize(hash, status string, meta notary.Meta) (*notary.Notarization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notarize", hash, status, meta)
	ret0, _ := ret[0].(*notary.Notarization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Notarize indicates an expected call of Notarize
func (mr *MockNotaryMockRecorder) Notarize(hash, status, meta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notarize", reflect.TypeOf((*MockNotary)(nil).Notarize), hash, status, meta)
}

// Authenticate mocks base method
func (m *MockNotary) Authenticate(hash string) (*notary.Notarization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", hash)
	ret0, _ := ret[0].(*notary.Notarization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate
func (mr *MockNotaryMockRecorder) Authenticate(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockNotary)(nil).Authenticate), hash)
}

// AuthenticateBatch mocks base method
func (m *MockNotary) AuthenticateBatch(hashes []string) ([]notary.Notarization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateBatch", hashes)
	ret0, _ := ret[0].([]notary.Notarization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateBatch indicates an expected call of AuthenticateBatch
func (mr *MockNotaryMockRecorder) AuthenticateBatch(hashes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateBatch", reflect.TypeOf((*MockNotary)(nil).AuthenticateBatch), hashes)
}

// History mocks base method
func (m *MockNotary) History(hash string) ([]*notary.Notarization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", hash)
	ret0, _ := ret[0].([]*notary.Notarization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History
func (mr *MockNotaryMockRecorder) History(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockNotary)(nil).History), hash)
}
