name: CI
on: [push, pull_request]
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v1
      - name: Build
        run: make -j all
      - name: Test
        run: make -j test
